### ISSUE TITLE
message: create block

### ISSUE THREAD

**Issue by aristov** [bem/bem-forms#1]
Block `message` is for show validation errors and other messages.

**Comment by zxqfox** [comment]
Всех устраивает API блока, [описанное в Blocks](https://github.com/bem/bem-forms/blob/dev/BLOCKS.md#%D0%91%D0%BB%D0%BE%D0%BA-message-extends-bemdom)?

**Comment by voischev** [comment]
А блок popup не устроит для вывода сообщений?

**Comment by verybigman** [comment]
Я сделаю и с ним. Там будет так, что вывод можно куда угодно делать. Шаблон
переопределяешь и все:)
Сб, 3 янв. 2015 г. в 19:25, Voischev Ivan <notifications@github.com>:
