### ISSUE TITLE
dirty fields mechanic

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#109]
Надо сделать механику грязных полей. В ангуляре есть такая штука. Надо для того, чтобы безопасно ходить по полям и не видеть сообщений про обязательность, например

**Comment by zxqfox** [comment]
Т.е. отключать нотификации у полей или формы в целом, отключая при этом нотификацию об ошибках (и/или проверки) и сабмиты?

**Comment by verybigman** [comment]
Типо того. Отключать пока юзер чего-нить не в колбасит в поле

**Comment by zxqfox** [comment]
:+1:

**Comment by voischev** [comment]
:+1:

**Comment by dragn** [comment]
I have this simple implementation in our project:

```javascript
FormField.decl({ block : this.name, modName : 'has-validate', modVal : true }, /** @lends form-field.prototype */{

    onSetMod : {
        'js' : {
            'inited' : function() {
                this.__base.apply(this, arguments);

                this.getControl().bindTo('control', 'blur', function(e) {
                    this._dirty = this._dirty || (this.getVal() != this._initVal);
                    this._dirty && this.validate();
                }.bind(this));

                this._initVal = this.getVal();
            }
        }
    },
});
```

The field is validated on blur, but only when the value differs from initial.

**Comment by zxqfox** [comment]
Я тут подумал. Кажется, тут были бы весьма кстати immutables.

**Comment by verybigman** [comment]
@dragn make pr? ;)
