### ISSUE TITLE
Move to incubator

### ISSUE THREAD

**Issue by blond** [bem/bem-forms#111]
https://github.com/bem-incubator

**Comment by zxqfox** [comment]
;-( это же git remote set-url надо будет запускать.

**Comment by verybigman** [comment]
С фига в инкубатор то?) Мы же уже в bem

**Comment by tadatuta** [comment]
Хочется, чтобы в bem был технофашизм и единые жесткие правила для всего кода.

**Comment by verybigman** [comment]
Таки может этим правила записать в виде jscs и всем станет жить хорошо?:) я же правильно понимаю, что когда в инкубаторе проект будет соответствовать правилам, он переедет в bem?

**Comment by tadatuta** [comment]
Тут речь не только про кодстайл, но в первую очередь про требования к архитектуре, соответствие принципам проектирования (да, мы их до сих пор не доформулировали, comming soon), поддержке (сборка, шаблонизаторы, браузеры, etc).

PS: все вышеперечисленное является необходимым, но не обязательно достаточным условием попадения в bem — мы должны еще мочь подхватить этот код или как минимум в нем разбираться. Текущая ситуация — @tavriaforever попробовал заиспользовать bem-forms на хакатоне и не осилил.

**Comment by verybigman** [comment]
Так себе показатель, конечно. А смысл инкубатора то в чем? Пока я вижу только слово bem в названии. Не там ни тут правил сформулированных нет. Как жить, что делать? Сейчас все выглядит так будто давайте все, что не попадя в инкубатор класть. А разницы с личным репозиторием никакой.

**Comment by tadatuta** [comment]
как я писал выше, правила в процессе формулирования, скоро покажем, обсудим и опубликуем.

инкубатор будет представлен на bem.info, в идеале аналогично тому, как представлены bem-components (но тут сильно зависит от того, готовы ли мейнтейнеры поддерживать необходимую инфраструктуру и писать доки). мы будем сами в него смотреть и будем про него везде рассказывать. так что главное отличие от личного репозитория — это наливаемый туда трафик от сообщества и возможность участникам проще повзаимодействовать.

впрочем, вся эта история обсуждаемая и, если у тебя есть какие-то пожелания/предложения — поделись.

**Comment by zxqfox** [comment]
@tadatuta Попробовал, и не написал ни одного issue! Как же так? ;-)

**Comment by voischev** [comment]
@tadatuta кайф :) ждем

**Comment by sipayRT** [comment]
> Попробовал, и не написал ни одного issue! Как же так? ;-)

Как всегда, все молчат и терпят ;)

@tadatuta @verybigman  мне кажется, что всех смущает именно название организации. Т.е. инкубатор - что-то недоделанное, полусырое. Но цель то была другая :)

**Comment by zxqfox** [comment]
@sipayRT В целом, меня не смущает. Если кого-то смущает — было бы интересно послушать доводы.

Я за то, чтобы свежее уносить в bem-incubator: это даст возможность видеть все имеющееся, чтобы не писать велосипеды, даст возможность получать больше ревью, заодно упростить публикацию на bem.info и унифицировать требования по документации и тестам, чтобы доки были на bem.info. В будущем, конечно, можно и bem-libraries сделать, или еще что-то ;-) Там видно будет.

**Comment by zxqfox** [comment]
@awinogradov А чего закрыл? Сырое же ;-)
