### ISSUE TITLE
Simple mods check

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#112]
Надо проверять модификаторы на наличие, чтобы предупреждать, а не падать в безызвестность.

**Comment by verybigman** [comment]
Ref #127

**Comment by dragn** [comment]
[Здесь](https://github.com/bem/bem-forms/blob/master/common.blocks/form-field/_has-validation/form-field_has-validation.browser.js#L60), очевидно, должны быть проверки на наличие мод-ра `type` (функции `getControl()`), и `message` (getMessage())
