### ISSUE TITLE
.getVal() on form returns string for checkbox fields

### ISSUE THREAD

**Issue by s-panferov** [bem/bem-forms#119]
~~~
{
    block : 'form-field',
    name : 'checkName',
    mods : { type : 'checkbox' },
    content : [
        {
            block : 'checkbox',
            mods : { size : 'l' },
            val : true,
            text : 'Some text inside'
        }
    ]
}
~~~

`.getVal()` on form produces `{checkName: "true"}` if checkbox is checked. I think that checkbox must produce only boolean value.

**Comment by zxqfox** [comment]
@s-panferov Agreed. Not sure where the error comes from.

**Comment by verybigman** [comment]
This problem can be solved in bem-components. Checkbox return val if it exist or "on" string if val is undefined.
