### ISSUE TITLE
Remove bind to submit from form

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#120]
https://github.com/bem/bem-forms/blob/master/common.blocks/form/_has-validate/form_has-validate.browser.js#L15-L17

**Comment by s-panferov** [comment]
It's not a bug, I think. It's just a change of the logic.

**Comment by verybigman** [comment]
Yes yes. I remove tag

**Comment by verybigman** [comment]
This is wrapper for BEM-event `submit`. Use `form.on('submit')`.
