### ISSUE TITLE
wrong regex for email

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#128]
1@1 is wrong email address, but validator don't know about this :(

Right regex: `^[0-9a-zA-Z]+([0-9a-zA-Z]*[-._+])*[0-9a-zA-Z]+@[0-9a-zA-Z]+([-.][0-9a-zA-Z]+)*([0-9a-zA-Z]*[.])[a-zA-Z]{2,6}$`

**Comment by zxqfox** [comment]
http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address

> There is no simple regular expression for this problem: see this fully RFC‑822–compliant regex, which is anything but simple. (It was written before the days of grammatical patterns.) The grammar specified in RFC 5322 is too complicated for primitive regular expressions.
> http://ex-parrot.com/~pdw/Mail-RFC822-Address.html
> http://www.ietf.org/rfc/rfc5322.txt

**Comment by zxqfox** [comment]
lel. http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address/1917982#1917982

**Comment by verybigman** [comment]
Scroll to the next comment) And please write your thoughts in comments)))

**Comment by zxqfox** [comment]
:+1: okey!
