### ISSUE TITLE
Disabled form-fields

### ISSUE THREAD

**Issue by dragn** [bem/bem-forms#132]
Disabled form-field should not get to form data in form.getVal()

**Comment by s-panferov** [comment]
-1 for this, because field is present on a form anyway.

**Comment by dragn** [comment]
How else would you remove some field from posted data?
Html inputs have the same behavior - inputs with 'disabled' attribute will not be submitted.

**Comment by dragn** [comment]
Correctly me if I'm wrong, but I think that getVal() method was intended to get serialized data for submission.

**Comment by zxqfox** [comment]
`getVal` should return value in any way, right?
But `form.getVal` shouldn't if field is disabled. So we can check field's modifier in `form` in `getVal`.

/cc @verybigman

**Comment by dragn** [comment]
I've made this override in `form`:
```
        getVal : function() {
            return this.getFields().reduce(function(res, field) {
                if (!field.getMod('disabled')) {
                    var name = field.getName();
                    if(name) res[name] = field.getVal();
                }
                return res;
            }, {});
        }
```

**Comment by zxqfox** [comment]
> `if (!field.getMod('disabled')) {`

why not `hasMod`?

**Comment by zxqfox** [comment]
> if(name) res[name] = field.getVal();

It will fail with `arr[1]` or `arr[key]` names.

**Comment by s-panferov** [comment]
@dragn if we do it that way, we need to add another method to receive the whole set of data, because 'disable' flag often used just for design reasons (e.g. in the case then you can't edit a field because of your permissions).

**Comment by dragn** [comment]
@s-panferov There is getFields()

**Comment by dragn** [comment]
@zxqfox Not `hasMod`, because you can set `disabled : false`

 > `if(name) res[name] = field.getVal();`

This code is currently there, I've just copied it.

**Comment by verybigman** [comment]
And `hasMod` return false

**Comment by verybigman** [comment]
-1 Disabled is readonly

**Comment by dragn** [comment]
Oh, come on. It's in HTML spec: http://www.w3schools.com/tags/att_input_disabled.asp.
Propose another solution if you don't like this. I want to exclude field from submit, how do I do that?

**Comment by zxqfox** [comment]
> Not hasMod, because you can set disabled : false

disabled : false is absence.

**Comment by dragn** [comment]
I got that, `hasMod`.
@zxqfox, what do you think about leaving disabled fields out of `form.getVal()`?

**Comment by dragn** [comment]
Let's add a new method `form.serialize()` that will get all fields except disabled and readonly.

**Comment by verybigman** [comment]
Why form val don't contain readonly or disabled form-fields vals? You can delete disabled or readonly properties from result object in `form.getVal()` by form-field name.

**Comment by zxqfox** [comment]
+1 for serialize

**Comment by s-panferov** [comment]
> Oh, come on. It's in HTML spec: http://www.w3schools.com/tags/att_input_disabled.asp.

Html spec behaves that way because there is no place where you can filter out content of your form. Here we all have JavaScript and we can just remove fields that we don't need from a result object. But I agreed, that compatibility with the spec is not bad, so I vote for a separate method.

**Comment by verybigman** [comment]
Disabled fields getVal now
