### ISSUE TITLE
label: create block

### ISSUE THREAD

**Issue by aristov** [bem/bem-forms#2]
Block `label` is for add labels to controls in some standard way.

**Comment by Coltspb** [comment]
Если что, label от инпута отрывал я, т.к. он усложняет верстку инпута и не имеет в себе почти никакого смысла.

**Comment by zxqfox** [comment]
@Coltspb С новым годом, Вань ;-) Я не думаю, что мы вернемся ни к элементу label блока input, ни — блока form, т.к. даже в случае формы мы легко можем позвать отрисовать label как отдельный блок, когда как обратное (звать form__label без form) не «по понятиям».

Спасибо за информацию.

**Comment by verybigman** [comment]
Давайте  сольем это уже в dev
