### ISSUE TITLE
Validation block and API

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-forms#27]
We using it as a mix for `input` (or similar) blocks right now:
```js
{
  block : 'input',
  mods : { theme : 'islands' },
  mix : [
    { block : 'form', elem : 'control' },
    { block : 'validation', mods : { numbers : true }, js : {/* validation params */} }
  ]
}
```

There is a lot of data that we should pass for each field and I really want to simplify it if possible.

Any guesses will help a lot.

The one that placed on the top of my mind probably have troubles with theme deps:
```js
{
  elem : 'control',
  mods : { type : 'text', theme : 'islands', size : 'l', validation : 'numbers' },
  js : { validation : { /* validation params */ } }
}
```

`control_validation_numbers` will require `validation_numbers` block, `form__control_type_text` will require `input` and `input_type_text`, and `form__control_theme_islands` will require `input_theme_islands`. Right?
Also it can internally regenerate the rest of needed bemjson by BH/BEMHTML but I'm afraid of missing deps here and need review.

I think that's all `validation` block needed to return some validation result. All other work with form should be placed in `form_validation`.

**Comment by zxqfox** [comment]
@verybigman To have a light form variant ;-)

**Comment by verybigman** [comment]
This resolve #5

**Comment by zxqfox** [comment]
And #14

**Comment by zxqfox** [comment]
```
module.require(['validate', 'validate_numbers'], function(validate, numbers) {
  validate.push(numbers(‘Херня’, fn(){})) };
  validate.run();
  new validate();
```

**Comment by verybigman** [comment]
[Solved](https://github.com/bem/bem-forms/commit/20a57705d7e1e5d381857acdab0dc2d2265df1ab)
