### ISSUE TITLE
form__field_validate

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#37]
Common mod for validate field value

Mod values
1. Card
2. Email
3. Money
4. Pattern
5. Numbers
6. Required

**Comment by zxqfox** [comment]
А почему так? А если я два захочу? Твой оригинальный вариант с `_{mod-validate}` был лучше, имхо.

**Comment by verybigman** [comment]
Идея я уже говорил тебе. Мне кажется, что на самом деле валидатор на филде нужен только один. А внутри него могут зваться все базовые, если тот самый один сложный.

**Comment by zxqfox** [comment]
Не выйдет так. Банальный пример: если мы указываем, что поле номер — то значение там может быть и тогда оно должно быть номер, а может его и не быть — тоже валидно, и вместе с этим можно примешать required. Иначе у нас каждый валидатор будет дублирован с required. А если еще какие-то появятся — будет вообще каша.

**Comment by verybigman** [comment]
Валидатор чисел может проверять только число, значет значение уже должно быть. Если его нет,то поле не валидно. Опциональность надо регулировать иначе. Это же только пока предложение. Это не решение пока еще. Обсуждаем

**Comment by zxqfox** [comment]
Окей, тогда как сделать опциональные поля с определенным форматом? ;-)

**Comment by verybigman** [comment]
Тут не совсем так. Надо модификатор optional. Если есть, то валидор запускать только при наличии значения. Если нет, то все тихо)

**Comment by zxqfox** [comment]
Окей, попробую пофантазировать в эту сторону.

В голову пришел еще один странный кейс, как-то совпадающий с `optional` (в случае, если либо пусто, либо валидатор): либо число, либо pattern с регуляркой, либо строка из 5 символов.

Т.е., если мы придумаем как красиво сделать ИЛИ, то можно будет сделать optional и с помощью него рулить необязательными полями.

**Comment by verybigman** [comment]
Да, отлично, давай подумаем
Чт, 15 янв. 2015 г. в 14:42, Alex Yaroshevich <notifications@github.com>:

**Comment by zxqfox** [comment]
Меня немного путает тот факт, что мы таким образом заставляем всегда указывать `optional: false`. Будет ли это удобно? По ощущениям, кол-во опциональных полей с общем объеме больше, чем обязательных. Т.е., логичнее указывать именно `required`. Не?

**Comment by verybigman** [comment]
Не знаю, может и логичнее. Но смысл один и тот же.

**Comment by zxqfox** [comment]
Ну это, знаете ли, бесспорно ;-) Я про сухой расчет кол-ва кода в целом. И по этим меркам required, имхо, выигрывает. Взять те же формы на клиентсайде во всяческих магазинах, где обязательных полей, де факто, должно быть минимум — имя, телефон или почта. Или формы в админке, где обязательных, опять же, меньше половины. И для этих кейсов очевидно, что required лучше.

С другой стороны, пытаясь встать на твою позицию, я вспоминаю формы в интернет-кабинете — тот же перевод требует заполнения 90% полей или даже всех. И в этом случае выигрывает optional.

Думаю, что нужен модификатор к форме, меняющий поведение по умолчанию (требование или опциональность полей).
