### ISSUE TITLE
Do we need `form-field` block?

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-forms#40]
1. `.form-field__message` vs `.form__field-message` or `.form__field .form__message` or `form__field_with-message`
2. `form-field_type_input` vs `form__field_type_input`
3. `form-field__control` vs `form__control`

etc.

**Comment by verybigman** [comment]
Now, i think right is:
`form__message`
&&
`form-field_type_*`
`form-field__message`

**Comment by verybigman** [comment]
[This](https://github.com/bem/bem-forms/tree/feature/form-field/common.blocks) is my example of this. Very cool!;)

**Comment by zxqfox** [comment]
Please move .js to .browser.js ;-)

**Comment by zxqfox** [comment]
So we need to move `__field` to private block `form-field` just because of `__message`?

Can we solve that somehow with `__field`? I don't see a big difference between `form__field` and `form-field`.

**Comment by verybigman** [comment]
Comfort development with stand alone block ;-)

**Comment by voischev** [comment]
> Please move .js to .browser.js ;-)
:+1:
