### ISSUE TITLE
form: add enctype attr

### ISSUE THREAD

**Issue by voischev** [bem/bem-forms#41]
Очень часто форма используется с `multipart/form-data`
```
{
            block : 'form',
            tag : 'form',
            attrs : {
                action : '/posts/',
                enctype : 'multipart/form-data',
                method : 'post'
            },
            content : []
}
```

**Comment by zxqfox** [comment]
Были мысли автоматически расчитывать этот `enctype` в зависимости от полей, которые там есть внутри, и проставлять метод `post`.

Т.е., грубо говоря, если есть `attach` в полях — то method должен быть post и enctype multipart/form-data.

Но можно и дать руками проставлять, если очень хочется.

**Comment by verybigman** [comment]
Руками лучше, само собой.

**Comment by zxqfox** [comment]
Closed via #44
