### ISSUE TITLE
set status mods on form-field message 

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#62]
Проблемы при пробрасывании положения `popup`. Как-то надо этот момент порешать. Положение у `popup`, стили у `message`, нужны стили от `message` на положение `popup`

**Comment by verybigman** [comment]
Проблемы при пробрасывании положения `popup`. Как-то надо этот момент порешать. Положение у `popup`, стили у `message`, нужны стили от `message` на положение `popup`

**Comment by zxqfox** [comment]
А дашь пример?

**Comment by verybigman** [comment]
Ну смотри. При активации ставим через `message`  `popup_visible` и если мы хотим увидеть `message` в виде ошибке ставим ему `message_error`. Все ок, пока стили не начинают зависеть от положения `popup`. Например вот как получается `message mesage_error popup popup_visible popop_derections_right-top`. Красиво написать стили для `message` не получиться. Решили пока установкой дополнительно `popup_error`. Но чето как-то не очень:)

**Comment by zxqfox** [comment]
Не очень понимаю, почему попап зависит от message, мессадж внутри или снаружи попапа?

**Comment by verybigman** [comment]
Попап миксован с мессаджем нынче. В противном случае. когда попап выдергивается из дома и ставиться в конец боди, стили на него влияют.
