### ISSUE TITLE
form-field type select

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#64]

**Comment by zxqfox** [comment]
я вот думаю, а мы не замучаемся?

**Comment by verybigman** [comment]
С чего вдруг?:)
Пн, 9 февр. 2015 г. в 13:19, Alexej Yaroshevich <notifications@github.com>:

**Comment by zxqfox** [comment]
Контролов... Их так много!

**Comment by verybigman** [comment]
Есть такое ощущение:) но базово столько сколько и в компонентах
Пн, 9 февр. 2015 г. в 13:23, Alexej Yaroshevich <notifications@github.com>:

**Comment by verybigman** [comment]
Контролы они такие... они такие разные все:)
