### ISSUE TITLE
validation: normalize API of validators and specs

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#69]
All error messages should be objects (?) or strings

Normalize all validators:
- [x] validation_card
- [ ] validation_numbers
- [ ] validation_email
- [ ] validation_money
- [ ] validation_pattern

**Comment by zxqfox** [comment]
Um?

**Comment by verybigman** [comment]
In card validation is object, but in others is string

**Comment by zxqfox** [comment]
We need specs for these validators.

**Comment by verybigman** [comment]
Yes!

**Comment by zxqfox** [comment]
#72

**Comment by verybigman** [comment]
Мы закрыли эту задачу же в #99 ?

**Comment by zxqfox** [comment]
@verybigman :+1: ога
