### ISSUE TITLE
collect fields in form on validate 

### ISSUE THREAD

**Issue by verybigman** [bem/bem-forms#79]
If i add new field, form don't know about it and validation don't work

**Comment by zxqfox** [comment]
How you doing it?

**Comment by verybigman** [comment]
`BEMDOM.after(*, BEMHTML.apply(field))`

**Comment by zxqfox** [comment]
We definitely need `Form.addField` method ;-) Can you make some specs for that?

**Comment by verybigman** [comment]
I think do this in #78 .addField

**Comment by verybigman** [comment]
:)
