### ISSUE TITLE
Why do we need 'has-validate' mod on form-field?

### ISSUE THREAD

**Issue by dragn** [bem/bem-forms#85]
Why do we need `has-validate` mod on form-field? The same thing is denoted by the presence of `validate` mod...
Moreover, I think it would be better to setup validators not through mods, but with a parameter, and support multiple validators, the example interface could be:
```js
{
    block : 'form-field',
    validators : [
        {
            type : 'required',
            message : 'Введите номер карты' // could contain error message
        },
        'card', // could be just string
        {
            type : 'regex',
            pattern : /^4.*/, // could contain extra parameters
            message : 'Тип карты не поддерживается'
    ]
}
```

**Comment by verybigman** [comment]
`has-validate` mod contain common methods for all validators. Yes it required dependency for all validators. We think forms can use form-fields without validators and source for validation not needed in bundles;)

**Comment by zxqfox** [comment]
We still thinking about interface for `bemtree` and your snippet can be a good start for it.

**Comment by verybigman** [comment]
Yes. We think about `form-field` generators by BEMTREE templates.

**Comment by verybigman** [comment]
@dragn close issue if we answer on your question, please.

**Comment by dragn** [comment]
> has-validate mod contain common methods for all validators. Yes it required dependency for all validators. We think forms can use form-fields without validators and source for validation not needed in bundles;)

I understand all that, but could not we put common logic in `validate` modifier? Couldn't we do this:
```js
FormField.decl({ modName : 'validate' }, {
    // ... common logic
});
```

**Comment by verybigman** [comment]
Only one problem - `form-field_required`. This modifier is not validate value. But your idea looks great for me. I think about it and required mod.
